markdown: kramdown

site_name : Hey, Get Back to Work
title : Hey, Get Back to Work!
description: You look distracted, get back to work!
url: http://heygetbackto.work

author : Brian Mitchell

exclude: ['README.md', '.gitignore', 'Gemfile', 'raw_resources']
